spring:
  cache:
    cache-names:
      - rate-limit-buckets
    caffeine:
      spec: maximumSize=100000,expireAfterAccess=3600s
#logging:
#  level:
#    ROOT: DEBUG
app:
  rate:
    limit: 2
bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/v1/area.*
      strategy: first
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: "getHeader('X-api-key')"
          execute-condition: "getHeader('X-api-key').startsWith('PX001-')"
          bandwidths:
            - capacity: 1
              time: 1
              unit: hours
        - cache-key: "getHeader('X-api-key')"
          execute-condition: "getHeader('X-api-key').startsWith('BX001-')"
          bandwidths:
            - capacity: 1
              time: 1
              unit: hours
        - cache-key: "getHeader('X-api-key')"
          bandwidths:
            - capacity: 1
              time: 1
              unit: hours
